[package]
name = "uefi-run"
description = "Run UEFI applications"
version = "0.3.0"
authors = ["Richard Wiedenhöft <richard@wiedenhoeft.xyz>"]
license = "MIT"
repository = "https://github.com/richard-w/uefi-run"
edition = "2018"

[dependencies]
clap = "2.32"
fatfs = "0.3"
fscommon = "0.1"
tempfile = "3.0"
